### ISSUE TITLE
kernel:unregister_netdevice: waiting for lo to become free. Usage count = 1

### ISSUE THREAD

**Issue by 1456764506** [Grokzen/docker-redis-cluster#100]
Base ENV CentOS7 
when I use "docker-compose build --build-arg "redis_version=4.0.1" redis-cluster" to build redis 
the problem appear 
“
Message from syslogd@localhost at Jul 29 20:03:22 ...
 kernel:unregister_netdevice: waiting for lo to become free. Usage count = 1
”
How can i solve this problem？

**Comment by Grokzen** [comment]
@1456764506 I dont know. This seems to be a problem on your system and/or docker itself. It has nothing todo with this image or repo really. I suggest you have to search for help on dev.to, stackoverflow or google to find out a solution to your problem.
