### ISSUE TITLE
how to set requirepass and the auth_pass for cluster

### ISSUE THREAD

**Issue by yzx1208yzx1208** [Grokzen/docker-redis-cluster#109]

**Comment by yzx1208yzx1208** [comment]
how to set requirepass and the auth_pass for cluster

**Comment by Grokzen** [comment]
@yzx1208yzx1208 This section is for reporting issues and not asking questions or for help. Please open up a new ticket in the `Discussion` tab that you will find up next to `Pull requests` tab here on github.
