### ISSUE TITLE
container restart uses old IP

### ISSUE THREAD

**Issue by michaelpog** [Grokzen/docker-redis-cluster#13]
When using this container in my docker compose file I've encountered the following issue. After calling docker-compose stop and then docker-compose start again. The data in redis-data/700*/ is retained in between restarts. (normal docker-compose behavior), the problem it leads to is that nodes that are started, read the data from previous restarts and exchange stale IP address. 
Every time docker compose starts the containers, the IP address of that container changes, however if the nodes use the old IP, the cluster fails.

I worked around it by adding:
command: 
            - "/bin/bash"
            - "-c"
            - "/bin/rm -f /redis-data/700*/*; /start.sh"
in my docker-compose file. However I think the proper solution would be changing original Dockerfile:

CMD ["/bin/bash", "-c", "/bin/rm -f /redis-data/700*/*; /start.sh"]

**Comment by Grokzen** [comment]
@michaelpog Can you please retry this with latest commits in master branch if you experience the same problems?

**Comment by Grokzen** [comment]
@michaelpog bump on my last msg that has not been answered

**Comment by michaelpog** [comment]
@Grokzen I apologize for the delay. Let me try

**Comment by michaelpog** [comment]
Seems to be working

**Comment by Grokzen** [comment]
@michaelpog Great, closing this issue then :)
