### ISSUE TITLE
Can I run a Redis cluster without a ".conf "configuration file like Mariadb Galera and just configure it all in the docker-comemater.yml file?

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [Grokzen/docker-redis-cluster#135]
I am an independent entrepreneur, and it takes a lot of time for operation and maintenance due to lack of manpower in the early stage. The cluster of Redis needs to create conf file and write docker-compose. yml file before deployment, so the operation needs to be repeated every time a host is added to the cluster.
I was wondering if I could do all the configuration with only one docker-compose. yml like "bitnami/mariadb-galera", so I could just change the cluster ID of each host I added to the cluster to solve the deployment problem.

**Comment by Grokzen** [comment]
@Conmi-WhiteJoker No i do not think you can do it like that. I do not know how mariadb-galeria docker image works tho so you will have to test this image and find out for yourself.
