### ISSUE TITLE
Cannot redirect when connecting from remote

### ISSUE THREAD

**Issue by BruceChen2017** [Grokzen/docker-redis-cluster#136]
When starting redis cluster container in remote server, then I try to connect from local machine. When redirecting, it always try to connect `172.17.0.2:xxxx`, then it cannot be connected. How to resolve this issue?

**Comment by Kindrat** [comment]
@BruceChen2017 Hey, so how did you do this?

**Comment by ccatterina** [comment]
@Kindrat I was looking for this feature too. It seems that is not supported https://github.com/Grokzen/docker-redis-cluster/issues/81#issuecomment-533887893

**Comment by BruceChen2017** [comment]
@Kindrat @ccatterina 
You can achieve this by creating network.
- create network: `sudo docker network create --subnet REMOTE_IP_SUBNET --ip-range REMOTE_IP_RANGE redis-cluster-network`
- connect by remote ip: `sudo docker run -dit --network=redis-cluster-network --ip=REMOTE_IP --name redis-cluster -p 70
00-7005:7000-7005 grokzen/redis-cluster`
