### ISSUE TITLE
Image with tag `latest` not latest

### ISSUE THREAD

**Issue by dkthezero** [Grokzen/docker-redis-cluster#153]
Reproduce:
Run: `docker pull grokzen/redis-cluster:latest`
After starting the container: check the log show - `Loading RDB produced by version 6.2.0`
Created: `Almost 2 years ago`

Expectation:
After starting the container: check the log show - `Loading RDB produced by version 7.0.7` as tag `7.0.7`

**Comment by Grokzen** [comment]
@dkthezero ah great catch

I updated it now with 7.0.8 and latest build correct. I saw that there is a bug in the invoke script that do not tag and pushes latest build correct so i need to fix that. But a new image is pushed with the correct version

![image](https://user-images.githubusercontent.com/892309/220313621-ab884e8a-ffbd-4ea8-8924-3c943a65f8d9.png)
