### ISSUE TITLE
Docker image with "latest" tag is not actually latest

### ISSUE THREAD

**Issue by KarelCemus** [Grokzen/docker-redis-cluster#162]
I noticed that [docker image published](https://hub.docker.com/layers/grokzen/redis-cluster/latest/images/sha256-bfdff783f81486e1f5b72a19f63fe4f87abc2feedfe6b690e7a86f7246571199?context=explore) as `latest` is not actualy latest, it is from `Feb 21, 2023 at 11:03 am` while [the latest version](https://hub.docker.com/layers/grokzen/redis-cluster/7.0.10/images/sha256-1e4b14cf748a9178a921d1cc784903eed586be700b04e49dc308a125babd8707?context=explore) is `7.0.10`.

I noticed this because the "latest" version doesn't include the fix of the protected mode from https://github.com/Grokzen/docker-redis-cluster/commit/d5a8e1221834318ce1a1e1283dc3c2840263de3d.

It took me some time to figure it out because I wasn't expecting that the latest is not actually latest, it would be nice fixing it.

**Comment by spencercjh** [comment]
I found the same problem.

**Comment by Grokzen** [comment]
@KarelCemus @spencercjh It should be fixed a while back by now, close:ing
