### ISSUE TITLE
servers can't agree on slots config after restart docker container.

### ISSUE THREAD

**Issue by myrfy001** [Grokzen/docker-redis-cluster#29]
I use the -v option to let docker save cluster data for me. but when the container restarted, servers can't agree on slot config.
```
      -v /data/redis/redis-data:/redis-data
      -v /data/redis/redis-conf/7000:/redis-conf/7000
      -v /data/redis/redis-conf/7001:/redis-conf/7001
      -v /data/redis/redis-conf/7002:/redis-conf/7002
      -v /data/redis/redis-conf/7003:/redis-conf/7003
      -v /data/redis/redis-conf/7004:/redis-conf/7004
      -v /data/redis/redis-conf/7005:/redis-conf/7005
      -v /data/redis/redis-conf/7006:/redis-conf/7006
      -v /data/redis/redis-conf/7007:/redis-conf/7007
```

**Comment by Grokzen** [comment]
@myrfy001 I need more output from this error if it still persist to be able to help.

But i should warn you that the intended purpose of this container is not to run it as a production version of a redis cluster or to maintain the configuration after the container has been stopped. I would suggest that you disable this option from your run arguments and to remove the old container and make a new one whenever you restart it.

Unless you can provide more data into when redis complains about i will close this issue.

**Comment by wormding** [comment]
127.0.0.1:7000> set a 1
(error) MOVED 15495 172.17.0.2:7002
How to solve this problem?

**Comment by Grokzen** [comment]
Closing this issue. This docker container is not intended to store the data between container starts as this container setup is not a production quality build and it will not be that either as the main purpose is to use it for development where throwaway is key.
