### ISSUE TITLE
Unable to use from remote machine

### ISSUE THREAD

**Issue by Grokzen** [Grokzen/docker-redis-cluster#3]
It has been found that if you start this docker image on machine `A` and then trying to connect to the redis instances from machine `B` then `RedisCluster` can't talk to all nodes in the cluster becuase `CLUSTER SLOTS` will tell the client that it should talk to `127.0.0.1` but there is no instance on that IP:PORT.

The one known solution from the client side is to provide the entire clusters IP:PORTs in `startup_nodes` and set `init_slot_cache=False` and the client should be able to talk to all nodes.

One solution that can be done in this repo is to remake the repo to work with 6 docker images and connect them externally with so it will connect with the correct IP addresses.

**Comment by Grokzen** [comment]
It is not known for sure yet but it could be that this problem has now been fixed with the fixes in PR #7 where the public IP address of the container is now used in the cluster setup. It might still be that a remote machine can't access it because a remote machine would require the IP address of the machine that is running the container and not just the public IP address of the container.

This should atleast make it easier to run a cluster client from another container on the same machine.

**Comment by bjackson** [comment]
I have this issue as well. In `start.sh`, `IP` is set by this command `ifconfig | grep "inet addr:17" | cut -f2 -d ":" | cut -f1 -d " "`. However, this is not the IP that the client needs when it sends a `MOVED`. This gives an IP that is only accessible on the host machine, such as X.X.0.X. I'm not too experienced with Docker, but it seems that what would need to be done is to have IP be set to the host machine's IP, and I'm not sure how to go about doing that.

**Comment by Grokzen** [comment]
@bjackson That hack in start.sh allows you to use a multi container solution for a redis cluster if you are running all machines on the same host and you are running your client on the same machine.

One solution (but bad) would be to allways know in before hand the host machine IP addresses for all nodes in the cluster and pass that information into your redis client and tell the client to not query for the cluster configuration. That would allow you to set anything you want and the client would be happy until you change something in the cluster or get a MOVED command and then it could be inconsistent depending on what IP it returns.

One other solution could be the new docker networking layer. I do not know how exactly it works yet or how it behaves across multiple hosts but it might help out somehow, i have to dig into that some more i guess.

A third but abit more difficult setup for a environment would be to register each node in a DNS and then in start.sh you query the external IP for the host and use that to bind together the cluster. That is alot more difficult to pull off and is not something easy to do in a out of the box solution.

Btw this container setup is also not really made for multi host solutions. It is a easy way to setup and test a redis cluster client locally or CI but it was not intended for production because of the difficult in the setup with IP addresses.

**Comment by laurie71** [comment]
This is an issue for me too. I was looking for a quick way to stand up a Redis cluster to test connectivity from my application. The problem is, I'm on OS X so I'm running Docker via `docker-machine`. As a result, both the IP address and ports that I need to connect to are different than what the Redis nodes report. I'm using the `ioredis` Node module to connect, and it doesn't seem to offer an equivalent to `init_slot_cache=False`. 

Has any solution been proposed to accommodate this use case? Any alternative solutions if this isn't going to be supported by this project?

**Comment by Grokzen** [comment]
@laurie71 Closing this one as invalid becuase the current scope for this repo is not to make this docker images compatible to be executed from a remote machine. It is intended to be used from the same machine as you run the container on.
