### ISSUE TITLE
(error) MOVED 15495 172.17.0.2:7002

### ISSUE THREAD

**Issue by wormding** [Grokzen/docker-redis-cluster#34]
127.0.0.1:7000> set a 1
(error) MOVED 15495 172.17.0.2:7002
How to solve this problem?

**Comment by Grokzen** [comment]
@wormding Use the following

```
$ redis-cli -c -p 7000
redis 127.0.0.1:7000> set foo bar
-> Redirected to slot [12182] located at 127.0.0.1:7002
OK
redis 127.0.0.1:7002> set hello world
```

you are not using the cluster mode on the redis-cli tool.

**Comment by wormding** [comment]
redis-cli -c  -p 7000
127.0.0.1:7000> set foo bar
-> Redirected to slot [12182] located at 172.17.0.2:7002

why will I got 172.17.0.2:7002 this? Thanks, buddy!!

**Comment by smdmts** [comment]
I'm facing the same issue on docker for mac. Is this docker's network problem in mac?

**Comment by smdmts** [comment]
I cleared with the similar product, that assigned fixed IP value as `127.0.0.1'.
- https://github.com/tommy351/docker-redis-cluster/blob/master/3.2/start.sh#L12

@Grokzen How about IP could be assigned by outside parameter?
- https://github.com/Grokzen/docker-redis-cluster/blob/master/docker-data/docker-entrypoint.sh#L24

**Comment by Grokzen** [comment]
@wormding You should really read up on the redis-cluster spec and basic docs before you continue. You can find it here https://redis.io/topics/cluster-tutorial . 

I can't help everyone who has basic redis cluster problems that is in no way related to this client lib. For that kind of help you have to ask in other forums/boards.

**Comment by Grokzen** [comment]
@smdmts No there is no relation between the problem wormding has and the problem you mentioned. Basically there is a difference between the IP address you connect to the cluster with, and the IP address that redis internally tracks each node with.

**Comment by wormding** [comment]
I have already fixed it out. @Grokzen  thanks a  lot~
