### ISSUE TITLE
Only one node is listening on 7000

### ISSUE THREAD

**Issue by SacDin** [Grokzen/docker-redis-cluster#35]
```
127.0.0.1:7000> cluster nodes
bf999ebbfaf3cba8239e6b16862dbeb2701da450 :7000 myself,master - 0 0 1 connected 0-5460
```

**Comment by Grokzen** [comment]
Well based on that you seem to have joined a cluster based on the slots split you have.

I would suggest that you try to connect to your cluster with the redis-cli client in cluster mode. `redis-cli -c 127.0.0.1` for example and try again.

**Comment by jwdstef** [comment]
How to make a fixed IP to redis.conf?

**Comment by Grokzen** [comment]
@jwdstef You either have to change the template file in this repo before you build the docker image here https://github.com/Grokzen/docker-redis-cluster/blob/master/docker-data/redis-cluster.tmpl or you have to start the container, change the config and restart the internal redis servers to get the new IP config. There is no real input way that enable it to change.
