### ISSUE TITLE
On relaunching  docker-redis-cluster its fail to rebuild clusters 

### ISSUE THREAD

**Issue by sinalkar** [Grokzen/docker-redis-cluster#38]
I need to persist the redis data so i bind outer **/mnt/data/** volume , My Docker compose as follows

> version: '2'
> services:
>   redis-cluster:
>     build:
>       context: .
>       args:
>         redis_version: '4.0.8'
>     hostname: server
>     volumes:
>         - /mnt/data/redis-data:/redis-data
>         - /mnt/logs:/logs
>         - /etc/localtime:/etc/localtime:ro
>     ports:
>       - '7000-7007:7000-7007'

On first fresh launch with command **docker-compose build** then **docker-compose up** all things working. If i stop services and relaunch again with command **docker-compose up**  its not working
here the logs 

> redis-cluster_1  | bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
> redis-cluster_1  | >>> Creating cluster
> redis-cluster_1  | [ERR] Node 0.0.0.0:7000 is not empty. Either the node already knows other nodes (check with CLUSTER NODES) or contains some key in database 0.
> redis-cluster_1  | ==> /var/log/supervisor/redis-1.log <==
> redis-cluster_1  | 57:C 21 Apr 18:35:11.523 # Configuration loaded
> redis-cluster_1  | 57:M 21 Apr 18:35:11.526 * No cluster configuration found, I'm fdcae75ea777f7f3359a92858a15cce1c260d1bd
> redis-cluster_1  | 57:M 21 Apr 18:35:11.612 * Running mode=cluster, port=7000.
> redis-cluster_1  | 57:M 21 Apr 18:35:11.612 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn isset to the lower value of 128.
> redis-cluster_1  | 57:M 21 Apr 18:35:11.612 # Server initialized
> redis-cluster_1  | 57:M 21 Apr 18:35:11.612 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fixthis issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> redis-cluster_1  | 57:M 21 Apr 18:35:11.612 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
> redis-cluster_1  | 57:M 21 Apr 18:35:11.612 * DB loaded from append only file: 0.000 seconds
> redis-cluster_1  | 57:M 21 Apr 18:35:11.612 # I have keys for unassigned slot 2376. Taking responsibility for it.
> redis-cluster_1  | 57:M 21 Apr 18:35:11.720 * Ready to accept connections
> redis-cluster_1  |
> redis-cluster_1  | ==> /var/log/supervisor/redis-2.log <==
> redis-cluster_1  | 59:M 21 Apr 18:35:11.720 * Running mode=cluster, port=7001.
> redis-cluster_1  | 59:M 21 Apr 18:35:11.720 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn isset to the lower value of 128.
> redis-cluster_1  | 59:M 21 Apr 18:35:11.720 # Server initialized
> redis-cluster_1  | 59:M 21 Apr 18:35:11.720 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fixthis issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> redis-cluster_1  | 59:M 21 Apr 18:35:11.720 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
> redis-cluster_1  | 59:M 21 Apr 18:35:11.720 * DB loaded from append only file: 0.000 seconds
> redis-cluster_1  | 59:M 21 Apr 18:35:11.720 # I have keys for unassigned slot 6918. Taking responsibility for it.
> redis-cluster_1  | 59:M 21 Apr 18:35:11.720 # I have keys for unassigned slot 6992. Taking responsibility for it.
> redis-cluster_1  | 59:M 21 Apr 18:35:11.720 # I have keys for unassigned slot 7735. Taking responsibility for it.
> redis-cluster_1  | 59:M 21 Apr 18:35:11.761 * Ready to accept connections
> redis-cluster_1  |
> redis-cluster_1  | ==> /var/log/supervisor/redis-3.log <==
> redis-cluster_1  | 58:C 21 Apr 18:35:11.533 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> redis-cluster_1  | 58:C 21 Apr 18:35:11.534 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=58, just started
> redis-cluster_1  | 58:C 21 Apr 18:35:11.534 # Configuration loaded
> redis-cluster_1  | 58:M 21 Apr 18:35:11.536 * No cluster configuration found, I'm 10674cb3321573f635bec757aa71f6dd30ee948d
> redis-cluster_1  | 58:M 21 Apr 18:35:11.703 * Running mode=cluster, port=7002.
> redis-cluster_1  | 58:M 21 Apr 18:35:11.704 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn isset to the lower value of 128.
> redis-cluster_1  | 58:M 21 Apr 18:35:11.704 # Server initialized
> redis-cluster_1  | 58:M 21 Apr 18:35:11.704 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fixthis issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> redis-cluster_1  | 58:M 21 Apr 18:35:11.704 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
> redis-cluster_1  | 58:M 21 Apr 18:35:11.704 * Ready to accept connections
> redis-cluster_1  |
> redis-cluster_1  | ==> /var/log/supervisor/redis-4.log <==
> redis-cluster_1  | 54:C 21 Apr 18:35:11.515 # Configuration loaded
> redis-cluster_1  | 54:M 21 Apr 18:35:11.517 * No cluster configuration found, I'm 9001f3f99e014fdb8a8478abc8bcc80a9a7d8b5d
> redis-cluster_1  | 54:M 21 Apr 18:35:11.612 * Running mode=cluster, port=7003.
> redis-cluster_1  | 54:M 21 Apr 18:35:11.612 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn isset to the lower value of 128.
> redis-cluster_1  | 54:M 21 Apr 18:35:11.612 # Server initialized
> redis-cluster_1  | 54:M 21 Apr 18:35:11.612 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fixthis issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> redis-cluster_1  | 54:M 21 Apr 18:35:11.612 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
> redis-cluster_1  | 54:M 21 Apr 18:35:11.612 * DB loaded from append only file: 0.000 seconds
> redis-cluster_1  | 54:M 21 Apr 18:35:11.612 # I have keys for unassigned slot 2376. Taking responsibility for it.
> redis-cluster_1  | 54:M 21 Apr 18:35:11.719 * Ready to accept connections
> redis-cluster_1  |
> redis-cluster_1  | ==> /var/log/supervisor/redis-5.log <==
> redis-cluster_1  | 53:M 21 Apr 18:35:11.572 * Running mode=cluster, port=7004.
> redis-cluster_1  | 53:M 21 Apr 18:35:11.572 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn isset to the lower value of 128.
> redis-cluster_1  | 53:M 21 Apr 18:35:11.572 # Server initialized
> redis-cluster_1  | 53:M 21 Apr 18:35:11.572 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fixthis issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> redis-cluster_1  | 53:M 21 Apr 18:35:11.572 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
> redis-cluster_1  | 53:M 21 Apr 18:35:11.572 * DB loaded from append only file: 0.000 seconds
> redis-cluster_1  | 53:M 21 Apr 18:35:11.572 # I have keys for unassigned slot 6918. Taking responsibility for it.
> redis-cluster_1  | 53:M 21 Apr 18:35:11.572 # I have keys for unassigned slot 6992. Taking responsibility for it.
> redis-cluster_1  | 53:M 21 Apr 18:35:11.572 # I have keys for unassigned slot 7735. Taking responsibility for it.
> redis-cluster_1  | 53:M 21 Apr 18:35:11.703 * Ready to accept connections
> redis-cluster_1  |
> redis-cluster_1  | ==> /var/log/supervisor/redis-6.log <==
> redis-cluster_1  | 56:C 21 Apr 18:35:11.533 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> redis-cluster_1  | 56:C 21 Apr 18:35:11.533 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=56, just started
> redis-cluster_1  | 56:C 21 Apr 18:35:11.533 # Configuration loaded
> redis-cluster_1  | 56:M 21 Apr 18:35:11.536 * No cluster configuration found, I'm a12500b7294d062ad406817025c9771209967e05
> redis-cluster_1  | 56:M 21 Apr 18:35:11.720 * Running mode=cluster, port=7005.
> redis-cluster_1  | 56:M 21 Apr 18:35:11.720 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn isset to the lower value of 128.
> redis-cluster_1  | 56:M 21 Apr 18:35:11.720 # Server initialized
> redis-cluster_1  | 56:M 21 Apr 18:35:11.720 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fixthis issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> redis-cluster_1  | 56:M 21 Apr 18:35:11.721 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
> redis-cluster_1  | 56:M 21 Apr 18:35:11.721 * Ready to accept connections
> redis-cluster_1  |
> redis-cluster_1  | ==> /var/log/supervisor/redis-7.log <==
> redis-cluster_1  | 55:C 21 Apr 18:35:11.530 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> redis-cluster_1  | 55:C 21 Apr 18:35:11.531 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=55, just started
> redis-cluster_1  | 55:C 21 Apr 18:35:11.531 # Configuration loaded
> redis-cluster_1  | 55:M 21 Apr 18:35:11.534 * Running mode=standalone, port=7006.
> redis-cluster_1  | 55:M 21 Apr 18:35:11.534 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn isset to the lower value of 128.
> redis-cluster_1  | 55:M 21 Apr 18:35:11.534 # Server initialized
> redis-cluster_1  | 55:M 21 Apr 18:35:11.534 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fixthis issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> redis-cluster_1  | 55:M 21 Apr 18:35:11.534 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
> redis-cluster_1  | 55:M 21 Apr 18:35:11.534 * Ready to accept connections
> redis-cluster_1  |
> redis-cluster_1  | ==> /var/log/supervisor/redis-8.log <==
> redis-cluster_1  | 60:C 21 Apr 18:35:11.534 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> redis-cluster_1  | 60:C 21 Apr 18:35:11.534 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=60, just started
> redis-cluster_1  | 60:C 21 Apr 18:35:11.534 # Configuration loaded
> redis-cluster_1  | 60:M 21 Apr 18:35:11.536 * Running mode=standalone, port=7007.
> redis-cluster_1  | 60:M 21 Apr 18:35:11.536 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn isset to the lower value of 128.
> redis-cluster_1  | 60:M 21 Apr 18:35:11.536 # Server initialized
> redis-cluster_1  | 60:M 21 Apr 18:35:11.536 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fixthis issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> redis-cluster_1  | 60:M 21 Apr 18:35:11.536 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
> redis-cluster_1  | 60:M 21 Apr 18:35:11.536 * Ready to accept connections

My Cluster Status ::

> redis-cli -c -p 7000
> 127.0.0.1:7003> cluster info
> cluster_state:fail
> cluster_slots_assigned:1
> cluster_slots_ok:1
> cluster_slots_pfail:0
> cluster_slots_fail:0
> cluster_known_nodes:1
> cluster_size:1
> cluster_current_epoch:0
> cluster_my_epoch:0
> cluster_stats_messages_sent:0
> cluster_stats_messages_received:0

**Comment by Grokzen** [comment]
This docker container was never intended to work with persistent data across multiple start/stop cycles and i have no intent to change it to help with that. This container was designed to be used for testing/demo purposes so you can very easy and quickly spin up a cluster and work with it.

Secondly, you have to consult the official redis docs on how to get a cluster running again after a full shutdown and startup as you have to do certain things to get the cluster back up again with old data.
