### ISSUE TITLE
The image on the docker hub does not contain redis 3.0

### ISSUE THREAD

**Issue by piront** [Grokzen/docker-redis-cluster#4]
Hi,

When I pull your docker image from the docker hub, the redis version is the 2.9.101 and not the 3.0.

**Comment by Grokzen** [comment]
Ah, good catch. 

I will rebuild the image and upload a new image tonight if i have time :]

**Comment by piront** [comment]
Thanks.

BTW, your makefile is really useful ! :')

**Comment by Grokzen** [comment]
@piront I have pushed a new image build, can you verify that it is the correct 3.0.0 release on your side?

**Comment by piront** [comment]
LGTM

> 20:M 09 Apr 16:46:49.962 # Server started, Redis version 3.0.0

Thanks !
