### ISSUE TITLE
docker-entrypoint.sh in the image of docker hub is NOT update to date

### ISSUE THREAD

**Issue by yuekui2** [Grokzen/docker-redis-cluster#41]
When I tried out the docker image in docker hub, I found the docker-entrypoint.sh is NOT update to date., missing the IP setup line. Could you help update it?

Thanks.
-Kui

**Comment by Grokzen** [comment]
What version are you trying to use from docker hub that is missing this?

**Comment by yuekui2** [comment]
Latest version


`C:\windows\system32>docker run -e "IP=127.0.0.1" -d grokzen/redis-cluster:latest
6bc56da8a817fa6a57110ac94b9acdbfa967f928c934d7276757574b1fffbdd2

C:\windows\system32>docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                     NAMES
6bc56da8a817        grokzen/redis-cluster:latest   "/docker-entrypoint.…"   5 seconds ago       Up 4 seconds        6379/tcp, 7000-7007/tcp   musing_galileo

C:\windows\system32>docker exec -it 6bc bash
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
root@6bc56da8a817:/data# cd /
root@6bc56da8a817:/# cat docker-entrypoint.sh
#!/bin/sh

if [ "$1" = 'redis-cluster' ]; then
    max_port=7007
    if [ "$CLUSTER_ONLY" = "true" ]; then
      max_port=7005
    fi

    for port in `seq 7000 $max_port`; do
`

**Comment by Grokzen** [comment]
@yuekui2 Found the problem. I was assuming that dockerhub tracked the last tag you pushed as the latest build similar to how it works locally. I pushed a new image to `:latest` tag and it should point to the same build as the latest redis tag 4.0.9.
