### ISSUE TITLE
why can not use "--network host" to run ?

### ISSUE THREAD

**Issue by jacksu** [Grokzen/docker-redis-cluster#42]
why can not use "--network host" to run

**Comment by Grokzen** [comment]
I do not understand what you want to do. Please elaborate what you want to do or i will close this issue.

**Comment by jacksu** [comment]
I use this command "docker run --rm -dit --network host grokzen/redis-cluster:3.2.11", but the redis cluster run is error.

**Comment by Grokzen** [comment]
Can you post the error?

**Comment by Grokzen** [comment]
You probably have issues with the IP lookup code in the bash script that helps the redis cluster to find out the IP address to use for `CLUSTER MEET` command.  I have no plans to solve this myself as this is not something i think is needed by default. If you however want to submit a Pull Request with some changes that is compatible with the old solution that will enable you to run on host network, i will review and consider it if it is sane.
