### ISSUE TITLE
Connection is getting timed out

### ISSUE THREAD

**Issue by abhay-at-eagle** [Grokzen/docker-redis-cluster#45]
My client application cannot connect to this redis cluster. It tries on all the nodes but connections gets tied out/
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at redis.clients.jedis.Connection.connect(Connection.java:184)
	... 74 common frames omitted

**Comment by abhay-at-eagle** [comment]
I installed and run  redis using this docker image : https://hub.docker.com/r/grokzen/redis-cluster/
I have redis client which connects to redis server and some stuff , but some how client is not able to connect to this redis-cluster.

Command I used to run is:
 docker run -d --restart=always --name redis_clustered -p 7000:7000 -p 7001:7001 -p 7002:7002 -p 7003:7003 -p 7004:7004 -p 7005:7005 -p 7006:7006 -p 7007:7007 -p 6379:6379 a7426da54f5a

Can you tell me if I am missing anything

**Comment by Grokzen** [comment]
What is your clientside code? How you connect to the cluster, what IP, what port? Are you using a Mac? What is the internal IP address inside the redis cluster (run CLUSTER INFO and CLUSTER SLOTS). Can you telnet to the cluster from inside the container? Can you telnet to it from the outside of the docker container?

**Comment by sgarg29** [comment]
yes I have the same problem. I am running on a mac. 
```
redis-cli -h localhost -p 9000
localhost:9000> CLUSTER INFO
cluster_state:fail
cluster_slots_assigned:1
cluster_slots_ok:1
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:1
cluster_size:1
cluster_current_epoch:0
cluster_my_epoch:0
cluster_stats_messages_sent:0
cluster_stats_messages_received:0
localhost:9000> CLUSTER SLOTS
1) 1) (integer) 1184
   2) (integer) 1184
   3) 1) ""
      2) (integer) 9000
      3) "622d8ae73548d9303d3ac790f8ba4adbeca4610f"
```

**Comment by sgarg29** [comment]
I spun up the cluster using the docker-compose file, and set the REDIS_CLUSTER_IP=0.0.0.0 before doing so in my environment ( as per instructions )

**Comment by sgarg29** [comment]
$ redis-cli -h localhost -p 9000
localhost:9000> SET FOO BAR
OK
localhost:9000> get FOO
"BAR"
localhost:9000> SET foo bar
(error) MOVED 12182 172.19.0.2:9002

this is what I get..

**Comment by abhay-at-eagle** [comment]
I was Mac book. I set up the cluster again with docker compose with following changes in docker-compose file : 
redis-cluster:
    environment:
     CLUSTER_ONLY: 'true'  
     IP: 0.0.0.0

It worked fine after that.

**Comment by sgarg29** [comment]
I did the same...but I get the following:
```
telnet localhost 9000
Trying 127.0.0.1...
Connected to localhost
Escape character is '^]'.
SET FOO BAR
+OK
GET FOO
$3
BAR
SET foo1 bar1
-MOVED 13431 127.0.0.1:9002
GET foo1
-MOVED 13431 127.0.0.1:9002
```

**Comment by abhay-at-eagle** [comment]
Did you add  CLUSTER_ONLY : 'true' docker file? That was the only addition i did in the docker file and it worked for me.

**Comment by sgarg29** [comment]
yeah looks like adding the IP env var worked..

**Comment by mrniko** [comment]
Unable to connect on Windows 7
```
docker run -e "IP: 0.0.0.0" -e CLUSTER_ONLY=true -i -t -p 7000:7000 -p 7001:7001 -p 7002:7002 -p 7003:7003 -p 7004:7004 -p 7005:7005 -p 7006:7006 -p 7007:7007 grokzen/redis-cluster
```

```
redis-cli -h localhost -p 7000
```
hangs forever

**Comment by Grokzen** [comment]
I have never tested/tried this on/from windows, so that itself could be an issue. The second part is that your config is probably wrong, try with `-e "IP=0.0.0.0"` instead. This is specified in the docs for that feature.

**Comment by stuckinforloop** [comment]
For anyone who's facing similar issue, I'm able to connect on port 7001 without much extra work required.

Try connecting to port 7001 instead of 7000.
