### ISSUE TITLE
cluster not starting

### ISSUE THREAD

**Issue by aksharp** [Grokzen/docker-redis-cluster#48]
**Error After connecting:**
127.0.0.1:7000> GET *
(error) CLUSTERDOWN The cluster is down

**docker-compose config**
version: '2'
services:
  redis-cluster:
    environment:
     IP: '0.0.0.0'
    build:
      context: .
      args:
        redis_version: '4.0.10'
    hostname: server
    ports:
      - '7000-7007:7000-7007'
    environment:
      CLUSTER_ONLY: 'true'

**Comment by Grokzen** [comment]
I have literally nothing to go on here becuase yoou have baiscally copied the docker-compose.yml file that is already checked into the repo and i know for a fact works. Check the logs for the container and look if you have any errors there when it tries to build up the cluster. Also if you can, try to download the container from docker-hub and run that one and see if you have the same issue or not
