### ISSUE TITLE
Update makefile to push 4.0.10 release

### ISSUE THREAD

**Issue by melinath** [Grokzen/docker-redis-cluster#53]
It looks like 4.0.10 is being built as part of build-4.0 but not pushed to dockerhub as part of push-releases, which may be why it's not present on dockerhub?

**Comment by Grokzen** [comment]
Did some updates to the Makefile and docs, and noticed that not all builds was properly pushed last time i updated it. They are now building and pushing so all images should be up on dockerhub shortly.

**Comment by Grokzen** [comment]
The specified release in the ticket was fixed now. There apears to be some issue with building the 5.0-rc* releases so need to investigate that further before they are updated on dockerhub. Closing this one as fixed for now.
