### ISSUE TITLE
redis changed the cluster form command

### ISSUE THREAD

**Issue by xpgongmath** [Grokzen/docker-redis-cluster#60]
using Grokzen/docker-redis-cluster on circleci.  Now we get 
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
WARNING: redis-trib.rb is not longer available!
You should use redis-cli instead.

All commands and features belonging to redis-trib.rb have been moved
to redis-cli.
In order to use them you should call redis-cli with the --cluster
option followed by the subcommand name, arguments and options.

**Comment by nishantgeorge** [comment]
#59 May be related

**Comment by Grokzen** [comment]
@xpgongmath @nishantgeorge The new 5.0.0 builds was broken. They are fixed now and ocnfirmed inside #59 that it works now with both :5.0.0 tag and :latest tag.
