### ISSUE TITLE
how to create docker container for every slave or master instead of unique port 

### ISSUE THREAD

**Issue by ElsayedAwdElsayed** [Grokzen/docker-redis-cluster#62]
I have started the redis cluster, it creates the redis nodes as different port on the same docker container .
How to generate docker container for every master or slave node as seperated machine , see below image for the created nodes 

![redis](https://user-images.githubusercontent.com/10967608/48550197-c0cd6180-e8da-11e8-9f6a-695c3a47d95e.PNG)

**Comment by Grokzen** [comment]
You can't do it in this repo and i have no plans on changing the build from the structure i have now to use seperate containers for every node.
