### ISSUE TITLE
This repo is not intended to be a production quality docker build. 

### ISSUE THREAD

**Issue by senzacionale** [Grokzen/docker-redis-cluster#64]
Hej,

I really like your redis cluster but I would like to know, why is not production ready?
"This repo is not intended to be a production quality docker build. "

Any speacial reason?

**Comment by Grokzen** [comment]
Like this line say `The main primary use for this container is to test redis cluster code.`

I also want to keep this repo as simple as i possible can, but still provide a working redis-cluster. I want the user to be able to spin up a working cluster within one single container and to be able to start using the clutser asap.

If i go down the path of trying to provide a redis-cluster container solution that should be production quality with security and best practises etc. and to be compatible with a few different docker cluster solutions with full docuemntation and configuration support for the different solutions, i have to rebuild the container into something else and i have no intent or want to build and/or maintain that kind of solution as i am not using this solution in my work or private life right now.

If you want to fork this repo and build something new that supports kubernetes or is tailored for your environment and setup, feel free to do o and host it as a separate project. I am sure there is a want and need for it, but it will not be part of this repo as things stand right now.
