### ISSUE TITLE
redis requires Ruby version >= 2.2.2.

### ISSUE THREAD

**Issue by senzacionale** [Grokzen/docker-redis-cluster#65]
Command

> docker build --build-arg redis_version=4.0.11 -t grokzen/redis-cluster .

Error during building the container

```
Step 13/22 : RUN gem install redis
 ---> Running in 395e4a2b054e
ERROR:  Error installing redis:
        redis requires Ruby version >= 2.2.2.
The command '/bin/sh -c gem install redis' returned a non-zero code: 1
```

**Comment by Grokzen** [comment]
@senzacionale Are you running on the latest git commit in this repo?

**Comment by Grokzen** [comment]
As the latest commit has the following line https://github.com/Grokzen/docker-redis-cluster/blob/master/Dockerfile#L24 has the redis version pinned to `-v 4.0.2` it would mean that you have either modified the Dockerfile yourself, or you are not running the latest git commit.
