### ISSUE TITLE
Not able to access from other machine

### ISSUE THREAD

**Issue by itthought** [Grokzen/docker-redis-cluster#68]
getting below error while fetching gata

-> Redirected to slot [2009] located at 127.0.0.1:7000
Could not connect to Redis at 127.0.0.1:7000: Connection refused
Could not connect to Redis at 127.0.0.1:7000: Connection refused

And while i run cluster node command getting below result
```
redis-cli -c -p 7000 -h 172.31.228.27
172.31.228.27:7000> cluster nodes
b111992ecf3bbdd52a0ec0f277d14a582f5d03c8 127.0.0.1:7001@17001 master - 0 1553773386203 2 connected 5461-10922
0e5f24ddcedeeac8d7164b870963f90a56713f5a 127.0.0.1:7004@17004 slave f0d3f731f1d79bd6f78ab0ad258edec3a8b5ab9e 0 1553773386203 5 connected
ef29c106a39a0798cb98d1279fafd867eb6ef9ec 127.0.0.1:7005@17005 slave 0233dabcd15666814dc5a1c2863a16bfb2c70b98 0 1553773387204 6 connected
f0d3f731f1d79bd6f78ab0ad258edec3a8b5ab9e 127.0.0.1:7002@17002 master - 0 1553773387104 3 connected 10923-16383
c02ca432ece94313bb258c34e814bc213a817a63 127.0.0.1:7003@17003 slave b111992ecf3bbdd52a0ec0f277d14a582f5d03c8 0 1553773385702 4 connected
0233dabcd15666814dc5a1c2863a16bfb2c70b98 127.0.0.1:7000@17000 myself,master - 0 1553773386000 1 connected 0-5460
```

**Comment by Grokzen** [comment]
Is your redis client code running on the same machine as your container? The IP address that redis returns from `cluster nodes` command is the address that your client must be able to understand and reach in order for the client to work.

**Comment by itthought** [comment]
No Its running on another machine.
I have started my cluster using below command

export REDIS_CLUSTER_IP=0.0.0.0
export REDIS_USE_SENTINEL=true
make build
make up

**Comment by Grokzen** [comment]
Running from another machine is not really supported. It is intended to start the cluster on the same machine that you are running your client on. You have to figure out how to get an IP address bound to the redis server itself that you can lookup from another machine. Redis is tricky in this way that it do not properly binds to an IP address that we want from the hostmachine itself.

**Comment by Grokzen** [comment]
Try to not use `export REDIS_CLUSTER_IP=0.0.0.0` and see if it binds to your docker ip address instead and if that helps. But docker by default do not have resolution of another machines docker ip addresses by default, unless you would run it within a system like kubernetes or similar that provides some form of DNS and ip resolution.
