### ISSUE TITLE
Make number of nodes configurable

### ISSUE THREAD

**Issue by viniciusd** [Grokzen/docker-redis-cluster#73]
This relates to #2 

In order to have my dev/test environment closer to production, it would be super helpful to have a similar number of masters and replicas.

In order to keep it totally compatible with previous versions, it should assume default values as the ones that are currently hardcoded

Thanks for the great work on this lean docker image for bootstrapping quick clusters :)

**Comment by Grokzen** [comment]
Relevant PR has been merged, closing this issue. Thank you again @viniciusd for providing this addition to this repo.
