### ISSUE TITLE
generate-supervisor-conf.sh does not account for changed INITIAL_PORT

### ISSUE THREAD

**Issue by mcnamaram** [Grokzen/docker-redis-cluster#78]
Discovered when trying to set this up with java testcontainers.  When i set the INITIAL_PORT env var to be the first in whatever the random generated port range is, the docker-entrypoint script correctly calculates the new $max-port value.  This value is then sent into the generate-supervisor-conf.sh but the seq line still has a hardcoded `7000` for the start value which will take a considerable time if the new max port is somewhere in the 30000s.
I tested this using `docker run -e "INITIAL_PORT=33011" grokzen/redis-cluster:latest`
and again with `docker run -e "INITIAL_PORT=6998" grokzen/redis-cluster:latest` and you can really see the difference in startup times (I gave up on the 33011 try).

**Comment by sola97** [comment]
and the [container image](https://hub.docker.com/r/grokzen/redis-cluster) need to update
