### ISSUE TITLE
Could not connect to Redis at 127.0.0.1:7000: Connection refused

### ISSUE THREAD

**Issue by itthought** [Grokzen/docker-redis-cluster#88]
Hi,
I am getting below error while fetching data from cluster remotely

**Comment by Grokzen** [comment]
@itthought There is nothing in this issue that i can work with and possibly help you with.

Please provide the following, what system/os you are running it on, what version of the container, are you inheriting your own container, if on mac, are you using the IP fix? are you trying to connect from another machine to the container?

Unless this is provided i will close the issue in a few days.

**Comment by itthought** [comment]
Hi Grokzen,

I am using Centos 7 os, I am accessing Redis cluster from remote machine. I am using below command to start Redis cluster containers

`export REDIS_CLUSTER_IP=0.0.0.0`
`make up`

Please find docker related details

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by Grokzen** [comment]
This is a common known issue with redis where redis itself will only track the internal ip addresses 127.0.0.1 betwen each node so when you run `CLUSTER INFO` on your inside of your cluster you will find the ip:s that redis tracks betwen nodes. So when your clients connect and asks the cluster for where the nodes is, they will get back "oh they are on `127.0.0.1:7000` so your client will try to connect to it. That usually works out when you run from the same local machine you run the container on, but when you are running from another machine, the networking and ip lookups do not work out inside this container. You have to sort it out on your own with networking and port forwarding etc to enable the container to work from another machine.

**Comment by PelamWolt** [comment]
Just a random note here in case somebody lands here from google with a similar problem than I had.

If you are using docker-compose and you have 1 container trying to connect to the redis-cluster container, consider setting `network_mode: host` on the connecting container. Then the redis-cluster ports will be mapped to its localhost and it will be able to connect to 127.0.0.1:7001 etc.

**Comment by Grokzen** [comment]
@PelamWolt Yes that is a good idea and makes things easier. There is always a issue with that redis-server internally tracks how to connect to each other node and the same IP:PORT is exposed out to each client and that is a very common problem that you describe where IP internally needs to be set to something else. Usually in regular deployments this is never an issue but this usually happens in installations like single VM/container setup:s

**Comment by danilofuchs** [comment]
> This is a common known issue with redis where redis itself will only track the internal ip addresses 127.0.0.1 betwen each node so when you run `CLUSTER INFO` on your inside of your cluster you will find the ip:s that redis tracks betwen nodes. So when your clients connect and asks the cluster for where the nodes is, they will get back "oh they are on `127.0.0.1:7000` so your client will try to connect to it. That usually works out when you run from the same local machine you run the container on, but when you are running from another machine, the networking and ip lookups do not work out inside this container. You have to sort it out on your own with networking and port forwarding etc to enable the container to work from another machine.

I'm trying to access the redis cluster container from inside another container, and am facing this exact issue. The Cluster advertises 127.0.0.1 which is unreachable from other containers in the same network.

My development setup is in MacOS, so `network_mode: host` is not available, but in linux CI it should work.

I believe setting `cluster-announce-ip` https://github.com/redis/redis/issues/7460 could work, but I would need to know the container IP inside the network (172.19.0.6) and doing so will make it impossible to connect to the cluster from outside the Docker network.

I'm not that experienced in Docker and Networking to find a viable solution, other than using a regular Redis instance during dev/e2e testing and a cluster in production.
