### ISSUE TITLE
unable to restart redis correctly

### ISSUE THREAD

**Issue by uraphaelp** [Grokzen/docker-redis-cluster#89]
I could launch a redis cluster successfully by both `docker run` and `docker-compose up` command. But I found that if I stopped the container and then restarted by `docker start` or `docker-compose start`, though nodes could be activated, they couldn't quite correctly form a well-performed cluster with 3-master and 3-slave. Instead they each are masters, with no link to other nodes.

**After restart nodes act like this:**
```
127.0.0.1:7001> CLUSTER NODES
42cbb35704d0e3e55b19062b5dfa50e64b75d7e8 :7001@17001 myself,master - 0 0 0 connected 7365
```
**before** they were quite correct seemed to me:
```
127.0.0.1:7001> CLUSTER NODES
a052960c0efe5fd3c8d51e2316fd38f7c084dfad 172.18.0.2:7005@17005 slave e7c1b986242757ce11e79c43721af4df07db5532 0 1574404342080 6 connected
2a43488a97d88fcab858de3629d9bb47ed8ee9a7 172.18.0.2:7004@17004 slave e78672c6e2094aea70694c859018d22d05b1f8c7 0 1574404341679 5 connected
dde131ae2a0649c600992a7f3b027a8e6d671110 172.18.0.2:7003@17003 slave 50c469b1adb539659efe0aef5762d67836c7fb18 0 1574404342683 4 connected
50c469b1adb539659efe0aef5762d67836c7fb18 172.18.0.2:7002@17002 master - 0 1574404341000 3 connected 10923-16383
e78672c6e2094aea70694c859018d22d05b1f8c7 172.18.0.2:7000@17000 master - 0 1574404343184 1 connected 0-5460
e7c1b986242757ce11e79c43721af4df07db5532 172.18.0.2:7001@17001 myself,master - 0 1574404341000 2 connected 5461-10922
```

Would anyone mind telling me what caused this. Do I have a way to have well-functional cluster after container restart?

**Comment by Grokzen** [comment]
I would think that redis internally has some node tracking and stuff and things so when the redis nodes start up again, i do think that redis needs other commands to basically go from a totally broken redis cluster to rebuild it again to a good initial state. Becuase when the cluster first starts, it tries to join up the nodes with eachother, but when the nodes think they are already part of a cluster, they can't join up to a new cluter again, but they need to have other commands run to basically rebuilt the clustet from the ground up. And that basically is not supported by this container to rebiuld a cluster thta has already been started and run at a earlier time. One solution that can be implemented is to remove all the nodes data and basically rebuild the cluster again from the ground up, yes that means all the data would be removed on each container start/restart, but it would start up a cluster each time.

**Comment by uraphaelp** [comment]
seems quite resonable. So maybe restarting the containers after they stop could somehow keep those configuration but configure it in a different way, I think I should `docker commit` to restore a stopped container and find out the specific reason.
