### ISSUE TITLE
How to persist data to the host

### ISSUE THREAD

**Issue by leishuiguang** [Grokzen/docker-redis-cluster#90]
How to persist data to the host

**Comment by Grokzen** [comment]
Use docker volumes and point a volume to the path inside the container that has the data that you want to persist. Read up on volumes on the official docker documentation https://docs.docker.com/storage/volumes/

**Comment by quydinhv** [comment]
hi @Grokzen, w.r.t. persisting data to the host, may I ask why do you delete the the `aof` files when starting up? Doesn't it remove all the persistent data of Redis from previous runs?

Below is snippet from [docker-entrypoint.sh](https://github.com/Grokzen/docker-redis-cluster/blob/master/docker-entrypoint.sh)
```
      if [ -e /redis-data/${port}/nodes.conf ]; then
        rm /redis-data/${port}/nodes.conf
      fi

      if [ -e /redis-data/${port}/dump.rdb ]; then
        rm /redis-data/${port}/dump.rdb
      fi

      if [ -e /redis-data/${port}/appendonly.aof ]; then
        rm /redis-data/${port}/appendonly.aof
      fi
```

**Comment by Grokzen** [comment]
@quydinhv The purpose for this image is to run unit tests, integration tests & demo scenarios. It was not built with the intent of running over multiple container starts. In practice if these files and data is not removed at container startup, the cluster will get into a bad and unusable state preventing it from being run. Changing this behavior is not something that will change within this container/git repo

**Comment by quydinhv** [comment]
Got it, thanks man!
