### ISSUE TITLE
Docker host networking mode

### ISSUE THREAD

**Issue by fkluthe** [Grokzen/docker-redis-cluster#91]
Hey, I have a question. I just stumbled upon this: 
```
Redis Cluster and Docker

Currently Redis Cluster does not support NATted environments and in general environments where IP addresses or TCP ports are remapped.

Docker uses a technique called port mapping: programs running inside Docker containers may be exposed with a different port compared to the one the program believes to be using. This is useful in order to run multiple containers using the same ports, at the same time, in the same server.

In order to make Docker compatible with Redis Cluster you need to use the host networking mode of Docker. Please check the --net=host option in the Docker documentation for more information.
```

From https://redis.io/topics/cluster-tutorial

How you worked around this problem? I not seeing a hint or something to use docker in host networking mode… Or is the redis documention outdated?

**Comment by Grokzen** [comment]
I dont use this container in host networking mode so i do not know how it would act or work or behave. The best action would be for you to try to start the container with that option and see if it work or not.

And if i understand the question correct, i dont work around this problem in this container at all becuse the cluster nodes will use whatever IP that redis thinks it should use on the inside based on what itself thinks should be used. If that is 127.0.0.1 or some other IP on the network, is currently up to redis to sort out.

I know this is kinda a requested feature to make it work to use this container outside of the machine you run it on, but i have not seen anyone propose a solution for it for this specific build/container.

**Comment by fkluthe** [comment]
Ah, got you, the described Problem in https://redis.io/topics/cluster-tutorial is only when you try to build an redis cluster with single containers...

Thx.

**Comment by JasonJunJun** [comment]
> Ah, got you, the described Problem in https://redis.io/topics/cluster-tutorial is only when you try to build an redis cluster with single containers...
> 
> Thx.

I don't quite understand, can you elaborate? Thanks in advance.

**Comment by fkluthe** [comment]
The Redis tutorial points out, that you cant easily set up a cluster by spinning up Redis Docker Containers in cluster mode. 

However, this is not what is happening in this project. This project is a redis cluster inside ONE Docker Container.  Therefore very helpful to try something out, but not for production.

From README: 
> This repo exists as a resource to make it quick and simple to get a redis cluster up and running with no fuzz or issues with mininal effort. The primary use for this container is to get a cluster up and running in no time that you can use for demo/presentation/development. It is not intended or built for anything else.

**Comment by Grokzen** [comment]
I could not have said it better myself @fkluthe and it is all correct what you said.
