### ISSUE TITLE
What are the other repos that are better suited for offering production ready redis cluster dockerfiles?

### ISSUE THREAD

**Issue by AdityaAnand1** [Grokzen/docker-redis-cluster#93]

**Comment by Grokzen** [comment]
I dont know

**Comment by AdityaAnand1** [comment]
Ok, no issues.

Just my two cents, this comes off a little hostile 😸 

![image](https://user-images.githubusercontent.com/13274079/71868235-53f6d580-3133-11ea-9be3-33fa6c5d18c0.png)

**Comment by Grokzen** [comment]
I dont care really, i have to state that in the readme to stop the influx of questions and requests and to help steer this repo into what i want this repo to be. Plenty of people have wanted this repo to switch and to alter into something that they can use for production use or other use-cases for their own case and it is not something that i want to support most of the time. If you have any suggestions in how to change the wording of it, please make a PR of the changes and i will look it over. It is not intended in any way to be hostile, i just write very litteraly and what is on my mind.
